# Use Node.js 14.x as the base image
FROM node:14

# # Set the working directory in the container
# WORKDIR /app

# # Copy the package.json and package-lock.json files to the container
# COPY package*.json ./

# # Install the dependencies
# RUN npm install

# # Copy the rest of the project files to the container
# COPY . .

# # Expose port 8080 for the web server
# EXPOSE 8080

# # Start the web server
# CMD [ "npm", "start" ]